set(SOURCES
    src/WinMain.cpp
    src/Window.cpp
    src/Game.cpp
    src/GameObjects/Snake.cpp
    src/GameObjects/PlayArea.cpp
    src/GameObjects/Food.cpp
    src/GameObjects/Collision/CollidableBase.cpp
    src/GameObjects/Collision/CollisionDetector.cpp
    src/State/GameStateMachine.cpp
    src/State/GameStateBase.cpp
    src/State/StartMenuState.cpp
    src/State/Playing.cpp
    src/State/GameOverState.cpp
    src/UI/Controls/Button.cpp
    src/UI/Controls/Label.cpp
    src/UI/StartMenu.cpp
    src/UI/Score.cpp
    src/UI/Scoreboard.cpp
)